version: "3.9"

services:
  react-portfolio:
    build: .
    container_name: react-portfolio
    restart: always
    expose:
      - "80"  # internal port in container, not mapped to host
    networks:
      - web
    environment:
      VIRTUAL_HOST: www.vtcoding.click
      LETSENCRYPT_HOST: www.vtcoding.click
      LETSENCRYPT_EMAIL: your-email@example.com

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "8080:80"   # map host 8080 to container 80
      - "8443:443"  # map host 8443 to container 443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    networks:
      - web

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    networks:
      - web

networks:
  web:
    driver: bridge
